services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src/:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    depends_on:
      - db
    command: sh -c "composer update && chown -R www-data:www-data /var/www/storage && php artisan key:generate && php-fpm"

  webserver:
    image: nginx:alpine
    container_name: nginx_webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  node:
    image: node:16-alpine
    container_name: node_container
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    command: sh -c "npm install && npm run dev"
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: user
    volumes:
      - dbdata:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: